### ISSUE TITLE
enhancement: nix flake

### ISSUE THREAD

**Issue by koalazub** [MilesCranmer/rip2#35]
Prefacing by saying I'm cognisant of this being a meme and also leading into the rabbit hole of integrating every build system known to the universe. 

Although it would be nice to have. I do understand if it's not a possibility

**Comment by kanielrkirby** [comment]
I can package it for Nix, I'm assuming it's just a simple cargo build. Flake should be pretty simple after that, just a callPackage. The way I've seen it done thus far is a flake.nix with the devShell, and a nix/default.nix with the package definition. I'll see about submitting a PR later tonight if that's cool.

**Comment by kanielrkirby** [comment]
Slight concern though, this would mean you'd need to update the vendor hash each time you deploy. There might be some way larger projects do that (something like nix-prefetch-url maybe?). I'll check around

**Comment by koalazub** [comment]
> I can package it for Nix, I'm assuming it's just a simple cargo build. Flake should be pretty simple after that, just a callPackage. The way I've seen it done thus far is a flake.nix with the devShell, and a nix/default.nix with the package definition. I'll see about submitting a PR later tonight if that's cool.

Depends on how you structure it and the assumptions made such as whether we need it to be backwards compatible with nix versions that don't have flakes enabled(2.4 I think is when they enabled it by default). That's what I find to be the only reason to have a `default.nix` file

You can package and build in the same flake and run it based on whether you want to develop or build. I tend to build flakes with everything in it as I only need the phases followed by the devShell declaration to simplify everything. My skill issue lies with deployment as I've never pushed anything to nixpkgs before. 

> Slight concern though, this would mean you'd need to update the vendor hash each time you deploy. There might be some way larger projects do that (something like nix-prefetch-url maybe?). I'll check around

I think that's the best approach too

**Comment by kanielrkirby** [comment]
Didn't have as much time as I thought, tomorrow is my day off so I'll do it then. 

But honestly the hardest part about sending it to nixpkgs directly is getting it reviewed before the other 6000 PRs and 8000 issues 😅

The concern with adding it directly to the repo is mostly for Miles and making sure he doesn't have to update the nix file each time manually. I'll have to see how other projects automate that step with maybe a git hook or workflow or something. Lemme know if you have inspiration anywhere for sure, didn't see many Rust examples in other CLIs (at least in the repo).

**Comment by koalazub** [comment]
Yeah totally understandable. You might be able to make the prefetch -> update the hash in an env var and then inject it into the flake? I haven't done that before so I'm just spitballing. I think a good source of inspiration would be https://github.com/helix-editor/helix/blob/master/flake.nix maybe? Or on a smaller scale: https://github.com/eza-community/eza/blob/main/flake.nix

The nice thing about nixpkgs is that you can approve it yourself and then it'll go through the publishing phase at some point. I did that for a package I wanted not too long ago. Plus their [Matrix for devs](https://matrix.to/#/#dev:nixos.org) is very helpful. I've got a bit of work that's time sensitive that I need to get done, but I'll definitely help when I can. 

Hope that info was useful

**Comment by kanielrkirby** [comment]
Super helpful actually, didn't know about the self-approvals, and hadn't gotten time to take a look at Helix yet. Swore I checked eza but I suppose not. Nix community is just so massive, can pretty much never know everything haha.

So it turns out packaging is different between `nixpkgs` and within the repo. If you're using `builtins.path` to source the package, it'll handle the hash implicitly, which is why neither repo *has* one. So my misunderstanding there haha.

**Comment by kanielrkirby** [comment]
Made a PR, lemme know if there's anything unordinary @koalazub, would be greatly appreciated.

**Comment by koalazub** [comment]
Thanks so much for spending time on this mate! Looks really good

**Comment by kanielrkirby** [comment]
Think it's time to close this one! @koalazub

**Comment by MilesCranmer** [comment]
Hey @kanielrkirby @koalazub I made a nixpkgs PR here: https://github.com/NixOS/nixpkgs/pull/353742. Please :+1: on that PR if you can so it gets prioritised for merging 🙂

**Comment by koalazub** [comment]
Awesome! And done

**Comment by koalazub** [comment]
You've got a fail on nixfmt. I think they're now leaning on `rfc-nixfmt` as the way forward from here on? Maybe give that a try and see how you go

**Comment by MilesCranmer** [comment]
Ah, I see. Let me try to fix it
