### ISSUE TITLE
Fish completions don't include filepaths unless a subcommand is first given

### ISSUE THREAD

**Issue by Mawdac** [MilesCranmer/rip2#39]
The completions for fish (haven't tested any others yet) only allow you to complete subcommands or options and not files/folders without first specifying a subcommand. This is pretty inconvenient for general `rip` usage

Ex.

```sh
touch mini
rip mi # tab to complete suggests `completions` instead of `mini`
rip help # tab after this and you get files/folders
```

I haven't dug into the completions but I imagine it would be a little tricky given they're generated from another lib it appears, haven't looked too deep - just wanted to report it. I get around it using `fzf` to pick things.

> Also thanks for bringing `rip` *back to life*

**Comment by MilesCranmer** [comment]
Thanks for the report!

For reference, the completions get generated by `clap_complete` here: https://github.com/MilesCranmer/rip2/blob/75ea37ef4ea16ae64809e9c50999d95fd6a809bd/src/completions.rs#L24

I _think_ I'm specifying subcommands correctly here: https://github.com/MilesCranmer/rip2/blob/75ea37ef4ea16ae64809e9c50999d95fd6a809bd/src/args.rs#L114.

When I try it on my machine with nushell, it seems to work correctly:

```nushell
touch mini
# rip mi <tab>
rip mini
```

So could be an issue in the clap completions generated for fish?

**Comment by MilesCranmer** [comment]
Some related issues:
- https://github.com/clap-rs/clap/issues/3917 (seems like the process of adding fish support is still ongoing)
- (maybe?) https://github.com/clap-rs/clap/issues/5242

**Comment by MilesCranmer** [comment]
Might be worth reporting it in the clap repo? I'm not sure if they are aware of this issue. But I don't think I can fix on rip side, it will need to be fixed upstream (unless I'm using clap complete wrong).

**Comment by Mawdac** [comment]
I had some time to play around with this, the completion that's generated includes `-f` (or `--no-files`) on the 3 subcommands

```fish
complete -c rip -n __fish_use_subcommand -f -a completions -d 'Generate shell completions file'
complete -c rip -n __fish_use_subcommand -f -a graveyard -d 'Print the graveyard path'
complete -c rip -n __fish_use_subcommand -f -a help -d 'Print this message or the help of the given subcommand(s)'
```

Removing those solves it, like you said this is clearly upstream - I am just not confident enough right this moment to open an issue in that repo since I don't really know rust. But I understand if you want to close this, I made a temp fix for this https://github.com/mawdac/fish-rip for anyone else who runs into it

**Comment by MilesCranmer** [comment]
Awesome!

I think it would be very appreciated by the clap team if you post an issue pointed it out. Even if someone has already posted a related issue, better safe than sorry :) If I was the maintainer I would definitely want to know about this!

**Comment by MilesCranmer** [comment]
You can always post a blank issue: https://github.com/clap-rs/clap/issues/new

<img width="492" alt="Screenshot 2024-06-26 at 13 38 00" src="https://github.com/MilesCranmer/rip2/assets/7593028/5ddbca4c-fdf8-4f79-91f4-f1845397c6f5">

I think you can just say exactly what you told me and copy-paste my responses and link this thread

**Comment by tesuji** [comment]
I'm agree that the generated completion should not ignore files. But if there is a file name `graveyard` just like the subcommand `graveyard`, what would rip2 do?

**Comment by MilesCranmer** [comment]
> But if there is a file name `graveyard` just when calling `rip2 graveyard`, what would rip2 do?

Good question.  Maybe we could have an error message that the user should write it as `./graveyard` due to an ambiguous file?

I think most of the time people just don't worry about this since it's rare enough. For example, you can technically `./-h` as a filepath. In which case most commands with a help flag would face the same question.

(By the way, `rip` is the binary name rather than `rip2`)

**Comment by Mawdac** [comment]
Thanks for the upstream fix @tesuji!

**Comment by MilesCranmer** [comment]
The release [v0.8.1](https://github.com/MilesCranmer/rip2/releases/tag/v0.8.1) is built with the latest clap. Thanks @tesuji!
