### ISSUE TITLE
rip undo, rip -s do not work

### ISSUE THREAD

**Issue by guytavor** [MilesCranmer/rip2#54]
```
$ cd test
$ ls

$ echo "hello" > hello
$ ls
hello

$ rip hello
$ ls

$ rip -s
deletion_time      	path

$ rip -u
ls
```
:(

**Comment by MilesCranmer** [comment]
What operating system, and what version of rip? Also, what file system?

**Comment by MilesCranmer** [comment]
Also what does `rip graveyard` print out?

**Comment by MilesCranmer** [comment]
Lastly can you try with a different graveyard directory set? See instructions on readme

**Comment by TomJo2000** [comment]
I seem to have run into the same issue while packaging this project for Termux.

<h1><em></em></h1> 

- Removing a file
- Restoring it
- And then removing it again

Consistently causes it to no longer be detected by `rip -s` or `rip -u`.
![image](https://github.com/user-attachments/assets/0463658d-ebd8-4c87-8fbf-3b8f7d850ca4)
I have tested this and confirmed the same behavior on both Arch Linux (x86_64, installed via `cargo install rip2`)
and Termux (AArch64, installed via `pkg i ./rip2_0.8.2_aarch64.deb` from the latest CI run of termux/termux-packages#21922)

**Comment by MilesCranmer** [comment]
Thanks for the MWE, that’s quite odd. I’ll take a look tomorrow.

**Comment by TomJo2000** [comment]
I wrote a quick `git bisect run` harness for this issue.
According to this cf632f180e4cfac79b29d5989116f3fcb89d2a69 is the culprit.

I unfortunately don't know enough Rust to know how or why that commit would cause this issue.

If you'd like to bisect the issue yourself you can use the instructions below:

<h1><em></em></h1> 

<details><summary>Test script: <code>ripme.sh</code></summary>
<p>

```bash
#!/usr/bin/env bash
# File: ripme.sh
# Validation script for https://github.com/MilesCranmer/rip2/issues/54
# Written by @TomJo2000, Mon Oct 21 2024
# Licensed under: The Unlicense
# License URL: https://choosealicense.com/licenses/unlicense/

function test_rip2() {
    local test_file test_graveyard list_cmd
    test_file='bisect-test.ext'
    test_graveyard="${TMPDIR:-/tmp}/bisect-graveyard"
    if command -v 'tree' &> /dev/null; then
        list_cmd=('tree' '-D')
    else
        list_cmd=('ls' '-lR')
    fi

    # check that we're in the rip2 repo's top directory
    [[ "$(git rev-parse --show-toplevel)" == "$PWD" ]] || {
        printf '%s\n' "Please run this test script from the top directory of the rip2 git repo."
        return 1
    }

    # clean up any previous test file/graveyard/build
    rm -vrf "$test_file" "$test_graveyard" 'target/release/rip'
    touch "$test_file"

    cargo build --release # build rip
    echo "Built $(./target/release/rip -V)"
    echo "Commit: $(git rev-parse HEAD)"

    # try to reproduce #54
    echo "First remove"
    ./target/release/rip --graveyard "$test_graveyard" "$test_file"
    ./target/release/rip -s --graveyard "$test_graveyard"
    echo "First restore"
    ./target/release/rip -u --graveyard "$test_graveyard"
    "${list_cmd[@]}" "$test_graveyard"
    echo "Second remove"
    ./target/release/rip --graveyard "$test_graveyard" "$test_file"
    ./target/release/rip -s --graveyard "$test_graveyard"
    echo "Second restore"
    ./target/release/rip -u --graveyard "$test_graveyard"
    "${list_cmd[@]}" "$test_graveyard"

    # Determine if the issue occurred
    if [[ -e "${test_graveyard}${PWD}/${test_file}" ]]; then
        echo "[ERROR]: '$test_file' is still in the graveyard."
        return 1
    fi

    if [[ ! -e "${PWD}/${test_file}" ]]; then
        echo "[ERROR]: '$test_file' was not restored, and is not in the graveyard."
        return 1
    fi

    echo "[SUCCESS]: '$test_file' was successfully restored"
}

test_rip2
```

</p>
</details>

- Copy test script into `ripme.sh` in the top directory of the `rip2` git repo.
- Designate a "bad" and "good" commit for the test range.
  - `git bisect start`
  - `git bisect bad HEAD`
  - `git bisect good v0.1.0`
- Run the bisect
  - `git bisect run ./ripme.sh`

**Comment by MilesCranmer** [comment]
Great, thanks!!

I've got it reproduced in an integration test so we can be sure the behavior doesn't come back. I'll PR soon hopefully.

**Comment by MilesCranmer** [comment]
Reverting that commit doesn't fix the issue sadly

**Comment by MilesCranmer** [comment]
0.8.3 will have this fix implemented (releases being generated currently). Thanks again for the report!!
